package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	_ "github.com/go-sql-driver/mysql"
)

type AutoGenerated struct {
	ErrorInfo struct {
		ErrorFlag    string `json:"errorFlag"`
		ErrorCode    string `json:"errorCode"`
		ErrorMessage string `json:"errorMessage"`
	} `json:"errorInfo"`
	ItemList []struct {
		Date      string `json:"date"`
		NameJp    string `json:"name_jp"`
		Npatients string `json:"npatients"`
	} `json:"itemList"`
}

type infection struct {
	Date      string `json:"date"`
	NameJp    string `json:"name_jp"`
	Npatients string `json:"npatients"`
}

// func main() {

// 	r := gin.Default()
// 	r.GET("/get", Import)
// 	r.Run()

// }

// func Import(c *gin.Context) {
// 	db, err := sql.Open("mysql", "root:password@(localhost:3306)/local?parseTime=true")
// 	if err != nil {
// 		log.Fatal(err)
// 	}
// 	defer db.Close()

// 	rows, err := db.Query("select data, name_jp, npatients from infection where date = 20221216")
// 	if err != nil {
// 		log.Fatal(err)
// 	}
// 	var resultInfection []infection

// 	for rows.Next() {
// 		infection := infection{}
// 		if err := rows.Scan(&infection.Date, &infection.NameJp, &infection.Npatients); err != nil {
// 			log.Fatal(err)
// 		}
// 		resultInfection = append(resultInfection, infection)
// 	}

// 	c.JSON(http.StatusOK, resultInfection)
// }

func main() { // データ取得、データベースに保存
	fmt.Println("データ取り込み中")
	url := "https://opendata.corona.go.jp/api/Covid19JapanAll"
	resp, _ := http.Get(url)
	if resp != nil {
		defer resp.Body.Close()
	}
	byteArray, _ := ioutil.ReadAll(resp.Body)

	jsonBytes := ([]byte)(byteArray)
	data := new(AutoGenerated)

	if err := json.Unmarshal(jsonBytes, data); err != nil {
		fmt.Println("JSON Unmarshal error:", err)
		return
	}
	// fmt.Println(data.ItemList)

	db, err := sql.Open("mysql", "root:password@(localhost:3306)/local?parseTime=true")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	delete, err := db.Prepare("DELETE FROM infection")
	if err != nil {
		log.Fatal(err)
	}
	delete.Exec()

	for _, v := range data.ItemList {
		insert, err := db.Prepare("INSERT INTO infection(data, name_jp, npatients) values (?,?,?)")
		if err != nil {
			log.Fatal(err)
		}
		insert.Exec(v.Date, v.NameJp, v.Npatients)
	}
	fmt.Println("データ取り込み完了")
}
